import { screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { withWord } from '../src/features/rooms/RoomPage';
import { loggedInApi, renderApp } from './helpers';

afterEach(() => vi.unstubAllGlobals());

const LAB3 = {
  id: 3,
  name: 'Lab 3',
  code: 'LAB3',
  block: 'B',
  floor: '1',
  color: '#2563eb',
  notes: null,
  directedBroadcast: null,
  batchSize: null,
  batchDelaySeconds: null,
  createdAt: 0,
  updatedAt: 0,
  deviceCount: 4,
};

function roomsApi(
  rooms: object[] = [LAB3],
  tags: object[] = [{ id: 7, name: 'professor', color: '#aa0000', deviceCount: 2 }],
) {
  return loggedInApi()
    .on('GET', '/api/rooms', { body: rooms })
    .on('GET', '/api/tags', { body: tags });
}

describe('rooms page (FR-008.1, FR-008.2)', () => {
  it('lists rooms with code, block, floor and machine count, plus tags', async () => {
    roomsApi();
    renderApp('/salas');
    expect(await screen.findByRole('link', { name: 'Lab 3' })).toHaveAttribute('href', '/salas/3');
    expect(
      screen.getByText(/Código LAB3 · Bloco B · Andar 1 · 4 máquina\(s\)/),
    ).toBeInTheDocument();
    expect(screen.getByText('professor')).toBeInTheDocument();
    expect(screen.getByText('2 máquina(s)')).toBeInTheDocument();
  });

  it('shows empty states for rooms and tags', async () => {
    roomsApi([], []);
    renderApp('/salas');
    expect(await screen.findByText('Nenhuma sala cadastrada')).toBeInTheDocument();
    expect(screen.getByText('Nenhuma etiqueta')).toBeInTheDocument();
  });

  it('creates a room (code generated by the server) and shows field errors for duplicates', async () => {
    let calls = 0;
    const api = roomsApi().on('POST', '/api/rooms', (body) => {
      calls++;
      return calls === 1
        ? {
            status: 409,
            body: { code: 'ROOM_NAME_DUPLICATE', message: 'Já existe uma sala com este nome.' },
          }
        : {
            status: 201,
            body: { ...LAB3, id: 9, name: (body as { name: string }).name, code: 'LAB9' },
          };
    });
    const user = userEvent.setup();
    renderApp('/salas');
    await user.click(await screen.findByRole('button', { name: 'Nova sala' }));
    const dialog = await screen.findByRole('dialog', { name: 'Nova sala' });
    await user.type(within(dialog).getByLabelText('Nome'), 'Lab 3');
    await user.click(within(dialog).getByRole('button', { name: 'Salvar' }));
    expect(
      await within(dialog).findByText('Já existe uma sala com este nome.'),
    ).toBeInTheDocument();
    await user.clear(within(dialog).getByLabelText('Nome'));
    await user.type(within(dialog).getByLabelText('Nome'), 'Lab 9');
    await user.type(within(dialog).getByLabelText('Máquinas por lote'), '5');
    await user.click(within(dialog).getByRole('button', { name: 'Salvar' }));
    expect(await screen.findByText('Sala "Lab 9" salva (código LAB9).')).toBeInTheDocument();
    const body = api.calls
      .filter((c) => c.method === 'POST' && c.path === '/api/rooms')
      .at(-1)?.body;
    expect(body).toMatchObject({ name: 'Lab 9', batchSize: 5, batchDelaySeconds: null });
    expect(body).not.toHaveProperty('code'); // empty code → server generates it
  });

  it('AC-008-01 deleting a room shows how many machines go to "Sem sala" and the affected schedules', async () => {
    const api = roomsApi()
      .on('GET', '/api/rooms/3/delete-impact', {
        body: { deviceCount: 4, schedules: [{ id: 1, name: 'Manhã' }] },
      })
      .on('DELETE', '/api/rooms/3', { status: 204 });
    const user = userEvent.setup();
    renderApp('/salas');
    await user.click(await screen.findByRole('button', { name: 'Excluir sala Lab 3' }));
    const dialog = await screen.findByRole('dialog', { name: 'Excluir sala' });
    expect(dialog).toHaveTextContent('4 máquina(s) irão para "Sem sala".');
    expect(dialog).toHaveTextContent('Manhã');
    await user.click(within(dialog).getByRole('button', { name: 'Excluir' }));
    expect(await screen.findByText('Sala "Lab 3" excluída.')).toBeInTheDocument();
    const del = api.calls.find((c) => c.method === 'DELETE');
    expect(del?.path).toBe('/api/rooms/3');
  });

  it('creates and deletes tags', async () => {
    roomsApi()
      .on('POST', '/api/tags', (body) => ({
        status: 201,
        body: { id: 8, color: '#64748b', deviceCount: 0, ...(body as object) },
      }))
      .on('GET', '/api/tags/7/delete-impact', { body: { deviceCount: 2, schedules: [] } })
      .on('DELETE', '/api/tags/7', { status: 204 });
    const user = userEvent.setup();
    renderApp('/salas');
    await user.click(await screen.findByRole('button', { name: 'Nova etiqueta' }));
    const dialog = await screen.findByRole('dialog', { name: 'Nova etiqueta' });
    await user.type(within(dialog).getByLabelText('Nome da etiqueta'), 'projetor');
    await user.click(within(dialog).getByRole('button', { name: 'Salvar' }));
    expect(await screen.findByText('Etiqueta "projetor" salva.')).toBeInTheDocument();
    await user.click(screen.getByRole('button', { name: 'Excluir etiqueta professor' }));
    const confirm = await screen.findByRole('dialog', { name: 'Excluir etiqueta' });
    expect(confirm).toHaveTextContent('A etiqueta será removida de 2 máquina(s).');
    await user.click(within(confirm).getByRole('button', { name: 'Excluir' }));
    await waitFor(() =>
      expect(screen.getByText('Etiqueta "professor" excluída.')).toBeInTheDocument(),
    );
  });
});

describe('room page /salas/:id (FR-008.3)', () => {
  const device = {
    id: 1,
    name: 'PC-01',
    mac: '00:AA:00:00:00:01',
    ip: '10.0.3.21',
    hostname: null,
    roomId: 3,
    tagIds: [],
    notes: null,
    enabled: true,
    manufacturer: null,
    model: null,
    serial: null,
    os: null,
    otherMacs: [],
    preparedAt: null,
    enrolledAt: null,
    createdAt: 0,
    updatedAt: 0,
    status: 'online',
    latencyMs: 1,
    lastSeenAt: 0,
    onlineSince: 0,
    everOnline: true,
    flags: { macLocallyAdministered: false, neverResponded: false },
  };

  it('AC-008-05 renders the room header, its devices and online count when opened directly', async () => {
    const api = roomsApi()
      .on('GET', '/api/rooms/3', { body: LAB3 })
      .on('GET', '/api/devices', { body: { items: [device], total: 1, page: 1, pageSize: 200 } });
    renderApp('/salas/3');
    expect(await screen.findByRole('heading', { level: 1, name: 'Lab 3' })).toBeInTheDocument();
    expect(await screen.findByText('PC-01')).toBeInTheDocument();
    expect(screen.getByText('1/4 ligadas')).toBeInTheDocument();
    const devicesCall = api.calls.find((c) => c.path === '/api/devices');
    expect(devicesCall).toBeDefined();
  });

  it('new devices default to this room', async () => {
    const api = roomsApi()
      .on('GET', '/api/rooms/3', { body: LAB3 })
      .on('GET', '/api/devices', { body: { items: [], total: 0, page: 1, pageSize: 200 } })
      .on('POST', '/api/devices', (b) => ({
        status: 201,
        body: { device: { ...device, ...(b as object) }, warnings: [] },
      }));
    const user = userEvent.setup();
    renderApp('/salas/3');
    expect(await screen.findByText('Nenhuma máquina nesta sala')).toBeInTheDocument();
    await user.click(screen.getByRole('button', { name: 'Adicionar máquina' }));
    const dialog = await screen.findByRole('dialog', { name: 'Novo dispositivo' });
    expect(within(dialog).getByLabelText('Sala')).toHaveValue('3');
    await user.type(within(dialog).getByLabelText('Nome'), 'PC-02');
    await user.type(within(dialog).getByLabelText(/^MAC/), '00:AA:00:00:00:02');
    await user.click(within(dialog).getByRole('button', { name: 'Salvar' }));
    await waitFor(() =>
      expect(api.calls.find((c) => c.method === 'POST')?.body).toMatchObject({ roomId: 3 }),
    );
  });

  it('shows "Sala não encontrada" for an unknown id', async () => {
    roomsApi()
      .on('GET', '/api/rooms/99', {
        status: 404,
        body: { code: 'NOT_FOUND', message: 'Item não encontrado.' },
      })
      .on('GET', '/api/devices', { body: { items: [], total: 0, page: 1, pageSize: 200 } });
    renderApp('/salas/99');
    expect(await screen.findByText('Sala não encontrada')).toBeInTheDocument();
  });
});

describe('room header labels', () => {
  it('adds "Bloco"/"Andar" only when the typed value does not already say it', () => {
    expect(withWord('Bloco', 'B')).toBe('Bloco B');
    expect(withWord('Bloco', 'Bloco A')).toBe('Bloco A');
    expect(withWord('Andar', '1')).toBe('Andar 1');
    expect(withWord('Andar', '1º andar')).toBe('1º andar');
  });
});
