/**
 * Phase 5 V-T01: every acceptance criterion of spec.md with the tests (file › title) or CI steps
 * that verify it, written to specs/validation-acs.md. Manual criteria are listed for the owner.
 *   node scripts/validation-report.ts
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { parseSpecAcs, parseTasks } from './check-trace.ts';

const root = join(import.meta.dirname, '..');
const AC_RE = /AC-\d{3}-\d{2}[ab]?/g;
const TITLE_RE =
  /\b(?:it|test|describe|It|Describe|Context)\b(?:\.\w+(?:\([^)\n]*\))?)*\s*\(?\s*(['"`])((?:(?!\1)[^\n])*)\1/g;

function files(dir: string, out: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    if (name === 'node_modules' || name === 'dist' || name.startsWith('.')) continue;
    const p = join(dir, name);
    if (statSync(p).isDirectory()) files(p, out);
    else if (/\.(?:test|spec)\.tsx?$|\.Tests\.ps1$/.test(name)) out.push(p);
  }
  return out;
}

/** AC id → evidence lines. */
export function evidence(
  sources: { path: string; text: string }[],
  workflows: { path: string; text: string }[],
) {
  const map = new Map<string, string[]>();
  const add = (id: string, line: string) => map.set(id, [...(map.get(id) ?? []), line]);
  for (const s of sources) {
    for (const m of s.text.matchAll(TITLE_RE)) {
      for (const id of new Set(m[2]?.match(AC_RE) ?? []))
        add(id, `\`${s.path}\` › ${m[2]!.replace(/\|/g, '\\|')}`);
    }
  }
  for (const w of workflows) {
    for (const line of w.text.split('\n')) {
      const m = /^\s*(?:-\s+)?name:\s*(.*)$/.exec(line);
      for (const id of new Set(m?.[1]?.match(AC_RE) ?? []))
        add(id, `CI \`${w.path}\` step “${m![1]!.trim()}”`);
    }
  }
  return map;
}

if (import.meta.main) {
  const spec = readFileSync(join(root, 'specs/spec.md'), 'utf8');
  const tasks = parseTasks(readFileSync(join(root, 'specs/tasks.md'), 'utf8'));
  const acs = parseSpecAcs(spec);
  const sources = ['apps', 'packages', 'scripts', 'test', 'e2e'].flatMap((d) =>
    files(join(root, d)).map((p) => ({
      path: relative(root, p).replace(/\\/g, '/'),
      text: readFileSync(p, 'utf8'),
    })),
  );
  const wfDir = join(root, '.github/workflows');
  const workflows = readdirSync(wfDir).map((n) => ({
    path: `.github/workflows/${n}`,
    text: readFileSync(join(wfDir, n), 'utf8'),
  }));
  const ev = evidence(sources, workflows);
  const taskOf = (id: string) =>
    tasks
      .filter((t) => t.acs.includes(id))
      .map((t) => t.id)
      .join(', ');
  const rows: string[] = [];
  let verified = 0;
  let manual = 0;
  let missing = 0;
  for (const ac of acs.values()) {
    const e = ev.get(ac.id) ?? [];
    const status = ac.manual ? 'manual (owner)' : e.length > 0 ? 'pass (automated)' : 'NO EVIDENCE';
    if (ac.manual) manual++;
    else if (e.length > 0) verified++;
    else missing++;
    rows.push(`| ${ac.id} | ${taskOf(ac.id)} | ${status} | ${e.slice(0, 3).join('<br>') || '—'} |`);
  }
  const out = `# Validation — acceptance criteria (V-T01)

Generated by \`node scripts/validation-report.ts\` from \`specs/spec.md\`, \`specs/tasks.md\`, test titles
and CI workflow steps. "pass (automated)" means the listed tests or CI steps exist and \`npm run
verify\` / CI ran them green on the commit this file was generated from; up to three pieces of
evidence are shown per criterion.

**${verified}** automated criteria with evidence · **${manual}** manual (owner checklist, V-T05) ·
**${missing}** without evidence.

| AC | Task | Status | Evidence |
|---|---|---|---|
${rows.join('\n')}
`;
  writeFileSync(join(root, 'specs/validation-acs.md'), out);
  process.stdout.write(`${verified} automated, ${manual} manual, ${missing} without evidence\n`);
  if (missing > 0) process.exitCode = 1;
}
